#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

META_FILE="packages/shared/src/build-meta.ts"

commit_short="unknown"
commit_full="unknown"
branch="unknown"
commit_count=0
dirty=false
build_time=$(date -u +%Y-%m-%dT%H:%M:%SZ)

if command -v git &>/dev/null && git rev-parse --short HEAD &>/dev/null 2>&1; then
  commit_short=$(git rev-parse --short HEAD)
  commit_full=$(git rev-parse HEAD)
  branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "detached")
  commit_count=$(git rev-list --count HEAD 2>/dev/null || echo 0)
  if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
    dirty=true
  fi
fi

cat > "$META_FILE" <<EOF
// Auto-generated by scripts/generate-build-meta.sh — DO NOT EDIT
// This file is gitignored and regenerated on every build

export const BUILD_META = {
  gitCommitShort: "${commit_short}",
  gitCommitFull: "${commit_full}",
  branch: "${branch}",
  commitCount: ${commit_count},
  dirty: ${dirty},
  buildTimeUtc: "${build_time}",
} as const;

export type SBuildBuildMeta = typeof BUILD_META;
EOF

echo "Generated $META_FILE: commit=${commit_short} count=${commit_count} branch=${branch} dirty=${dirty}"
